### ISSUE TITLE
problem with "room" and "reservation" plugins

### ISSUE THREAD

**Issue by tontonrico** [C-Duv/glpi-room#9]
hi, when I use Room plugin with the Resertvation plugin, there is an error when I click directly on one room object (not if I select it) : there is a redirection to /glpi/front/pluginroomroom.form.php wich does not exist. I think it comes from a bad item identification in the Room plugin. Maybe this is not the case (I am not developper :-( )

Best Regards

**Comment by C-Duv** [comment]
Which version (of GLPI and the plugin) are you using?
I have no issue with GLPI v0.90.5 and room v3.0.4b2 nor with GLPI v9.1.

**Comment by tontonrico** [comment]
the versions used are : glpi 9.1 - room 3.0.4b2 - reservation 1.3.2

**Comment by C-Duv** [comment]
I can reproduce the issue: you are on page ".../plugins/reservation/front/reservation.php" and click on the name of a room in the list just above the "Réserver" button?

[_Reservation_ plugin](https://forge.glpi-project.org/projects/reservation) v1.3.2 is not (said) compatible with GLPI v0.90, so I tested with _Reservation_ v1.3.3 (just have to adapt versions in `plugin_reservation_check_prerequisites()` in `hook.php` file) (on GLPI v9.1).

Problem is in _Reservation_ plugin, file `inc/reservation.class.php`, line 244 (see it on [plugin's forge](https://forge.glpi-project.org/projects/reservation/repository/entry/trunk/inc/reservation.class.php?utf8=%E2%9C%93&rev=23#L244)), it does not rely on core method `CommonGLPI::getFormUrl()` as it should. You can try to fix it there is you want but there is nothing I do.
